version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      radix-ui:
        patterns:
          - '@radix-ui/*'
      tanstack:
        patterns:
          - '@tanstack/*'
      trpc:
        patterns:
          - '@trpc/*'

  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
    groups:
      aws-sdk:
        patterns:
          - '@aws-sdk/*'
      bull:
        patterns:
          - 'bullmq'
          - '@bull-board/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
